services:
  postgres:
    image: postgres
    container_name: expense-postgres
    environment:
      POSTGRES_DB: expense_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 9936287082
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  expense-app:
    image: yourusername/expense-tracker-app:44b49211f7d639d6e09a806e42e5644652dcfe55
    container_name: expense-app
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      postgres:
        condition: service_healthy
    
